<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Features\Administracion\Users\NewFolder1\**" />
    <EmbeddedResource Remove="Features\Administracion\Users\NewFolder1\**" />
    <None Remove="Features\Administracion\Users\NewFolder1\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cepheus.Domain\Cepheus.Domain.csproj" />
    <ProjectReference Include="..\Cepheus.Transversal.Mediator\Cepheus.Transversal.Mediator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Facturacion\Transacciones\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
